from tkinter import *
import time
root = Tk()
root.title("Aidan.Co Launcher")
root.geometry('445x130')
colour=("blue")
colour2=("grey")
Limg = PhotoImage(file='ATindustriesLogo.png')
LlabelImg = Label(image=Limg,bg=colour)
LlabelImg.place(x=370)
root.configure(background=colour)
Llabel = Label(root,text="setup ready",bg=colour,fg=colour2)
Llabel.place(x=1,y=50)
def launching():
    Lbutton.destroy()
    Llabel.configure(text="beggining setup")
    root.update()
    time.sleep(2)
    Llabel.configure(text="protected by P.E.S.T")
    root.update()
    time.sleep(2)
    Llabel.configure(text="Made by AidanCo")
    root.update()
    time.sleep(2)
    Llabel.configure(text="a subsidary of ATindustries")
    root.update()
    time.sleep(2)
    Llabel.configure(text="all rights reserved")
    root.update()
    time.sleep(2)
    Llabel.configure(text="setup complete")
    root.update()
    time.sleep(2)
    Llabel.configure(text="firering photon cannons")
    time.sleep(2)
    root.update()
    Llabel.configure(text="Launching")
    time.sleep(2)
    root.update()
    Llabel.destroy()
    from AidanColauncher import begin
    begin(root)
Lbutton = Button(root, text="Login",width=10, height=1,command=launching,bg=colour2,activebackground=colour,fg=colour,activeforeground=colour)
Lbutton.place(x=1,y=1)
root.mainloop()